spring:
  datasource:
    jdbcUrl: jdbc:log4jdbc:mariadb://61.75.35.56:3306/t1?serverTimezone=asia/seoul
    username: glovis-user
    password: ishift7150!
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 10
      poolName: pool01
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      file-size-threshold: 5MB
      max-request-size: 100MB
      resolve-lazily: false

  jpa:
    database-platform: org.hibernate.dialect.MariaDB10Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
      # ddl-auto: update

  profiles:
    active: none

server:
  port: 35060

jwt:
  header: Authorization
  secret:
    key: C&F)J@NcRfUjXn2r5u8x/A?D*G-KaPdS

# 경로 관련
filepath:
  root: "/Users/ijaewon"
  contentDir: "/data/files/"
  thumbnailContentDir: "/data/images/"

logging:
  config: classpath:logback-spring.xml
